const state={providers:[],last:null};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const HISTORY_KEY='nutev_web_search_history_v1';

function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}
function saveHistory(item){const h=history().filter(x=>x.search_id!==item.search_id);h.unshift({search_id:item.search_id,query:item.query,created_at:item.created_at,unique_records:item.unique_records,returned_records:item.returned_records});localStorage.setItem(HISTORY_KEY,JSON.stringify(h.slice(0,30)))}
function switchView(name){$$('.view').forEach(x=>x.classList.add('hidden'));$$('.nav-item[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$(`#${name}View`).classList.remove('hidden');if(name==='history')renderHistory()}

async function init(){
  $$('.nav-item[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
  $('#clearHistory').onclick=()=>{localStorage.removeItem(HISTORY_KEY);renderHistory()};
  try{const [health,providers]=await Promise.all([fetch('/api/health').then(r=>r.json()),fetch('/api/providers').then(r=>r.json())]);$('#health').textContent=health.status==='ok'?'engine conectado':'engine indisponível';$('#health').classList.add(health.status==='ok'?'ok':'bad');state.providers=providers.providers||[];renderProviders()}catch(e){$('#health').textContent='engine indisponível';$('#health').classList.add('bad');$('#searchBtn').disabled=true}
  $('#searchBtn').onclick=runSearch;
  const params=new URLSearchParams(location.search);if(params.get('q')){$('#question').value=params.get('q');runSearch()}
}
function renderProviders(){const root=$('#providerGrid');root.innerHTML=state.providers.map(p=>`<label class="provider-chip"><input type="checkbox" value="${esc(p.id)}" checked> ${esc(p.label)}</label>`).join('');$('#searchHint').textContent=`${state.providers.length} fontes conectadas no modo web`}
function selectedProviders(){return $$('#providerGrid input:checked').map(x=>x.value)}
async function runSearch(){const query=$('#question').value.trim();if(!query)return alert('Digite uma pergunta de busca.');const providers=selectedProviders();if(!providers.length)return alert('Selecione pelo menos uma fonte.');const btn=$('#searchBtn');btn.disabled=true;$('#searchState').className='loading';$('#searchState').textContent='Buscando nas fontes selecionadas, deduplicando e priorizando referências…';$('#summary').classList.add('hidden');$('#results').innerHTML='';try{const res=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,providers,per_provider:Number($('#perProvider').value||25),max_results:Number($('#maxResults').value||100)})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.error||'Falha na busca');state.last=data;saveHistory(data);renderSearch(data)}catch(e){$('#searchState').className='error';$('#searchState').textContent=`Falha na busca: ${e.message}`}finally{btn.disabled=false}}
function renderSearch(data){$('#searchState').classList.add('hidden');const failed=(data.failed_providers||[]).length;$('#summary').classList.remove('hidden');$('#summary').innerHTML=`<div class="summary-grid"><div class="kpi"><strong>${data.unique_records}</strong><span>referências únicas</span></div><div class="kpi"><strong>${data.records_before_dedup}</strong><span>antes da deduplicação</span></div><div class="kpi"><strong>${data.returned_records}</strong><span>exibidas</span></div><div class="kpi"><strong>${failed}</strong><span>fontes com falha</span></div></div><div class="provider-status">${(data.providers||[]).map(p=>`<span class="provider-badge ${p.status==='failed'?'failed':''}" title="${esc(p.error||'')}">${esc(p.label)} · ${esc(p.status)} · ${p.returned}</span>`).join('')}</div><div class="warning">${esc(data.ranking_warning)} ${(data.interactive_limitations||[]).map(esc).join(' ')}</div>`;$('#results').innerHTML=(data.results||[]).map(resultCard).join('')||'<div class="card">Nenhuma referência foi recuperada pelas fontes selecionadas.</div>'}
function resultCard(r){const href=r.doi?`https://doi.org/${String(r.doi).replace(/^https?:\/\/doi\.org\//i,'').replace(/^doi:/i,'')}`:(r.url||'');const id=r.pmid?`PMID ${r.pmid}`:(r.doi?`DOI ${r.doi}`:'');return `<article class="result-card"><div class="result-top"><div class="rank">${esc(r.reference_rank)}</div><div style="flex:1"><h3>${esc(r.title||'(sem título)')}</h3><div class="meta"><span>${esc(r.journal||'—')}</span><span>${esc(r.year||'—')}</span><span>${esc(r.source_provider||r.source||'')}</span><span>${esc(id)}</span></div></div><div class="score"><strong>${Number(r.reference_score||0).toFixed(1)}</strong><span>prioridade</span></div></div>${r.abstract?`<div class="abstract">${esc(r.abstract).slice(0,900)}${String(r.abstract).length>900?'…':''}</div>`:''}${href?`<div class="links"><a href="${esc(href)}" target="_blank" rel="noopener noreferrer">Abrir fonte ↗</a></div>`:''}</article>`}
function renderHistory(){const root=$('#historyList'),h=history();if(!h.length){root.innerHTML='<p style="color:#667572">Nenhuma busca salva ainda.</p>';return}root.innerHTML=h.map(x=>`<div class="history-item"><button data-q="${esc(x.query)}"><strong>${esc(x.query)}</strong><br><span style="color:#667572;font-size:.78rem">${x.unique_records} únicas · ${x.returned_records} exibidas</span></button><span class="history-meta">${esc(new Date(x.created_at).toLocaleString('pt-BR'))}</span></div>`).join('');root.querySelectorAll('button[data-q]').forEach(b=>b.onclick=()=>{$('#question').value=b.dataset.q;switchView('search');runSearch()})}
init();
