const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const fmt=value=>new Intl.NumberFormat('pt-BR').format(Number(value||0));
const labels={nutrition_assessment:'Avaliação nutricional',dietary_counseling:'Aconselhamento alimentar',nutrition_prescription:'Prescrição nutricional',monitoring_follow_up:'Monitoramento / seguimento',food_skills_competencies:'Competências e habilidades alimentares',food_literacy:'Food / nutrition literacy',social_context:'Contexto social da alimentação',food_based_guidance:'Orientação baseada em alimentos',nutrition_care_process:'Nutrition Care Process',lifestyle_medicine:'Medicina do Estilo de Vida',implementation_practice:'Implementação na prática'};
const classLabels={food_based_dietary_guideline:'FBDG',clinical_practice_guideline:'Diretriz clínica',consensus_statement:'Consenso',position_statement:'Position statement',framework_model:'Framework/modelo',competency_curriculum:'Competências/currículo',implementation_evaluation:'Implementação',primary_randomized:'Randomizado',primary_observational:'Observacional',primary_qualitative:'Qualitativo',evidence_synthesis:'Síntese de evidência',review:'Revisão',guidance:'Guidance',unclassified:'Não classificado'};
let articles=[];
let selected=new URLSearchParams(location.search).get('domain')||'';

function syncDomainUrl(){const params=new URLSearchParams(location.search);if(selected)params.set('domain',selected);else params.delete('domain');history.replaceState(null,'',`${location.pathname}${params.toString()?`?${params}`:''}`)}

async function load(){
  try{
    const response=await fetch('/agent-context/article1/ARTICLE_SUMMARIES.jsonl',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);
    articles=(await response.text()).split(/\r?\n/).filter(Boolean).map(JSON.parse);
    const available=new Set(articles.flatMap(row=>row.review_profile?.operational_domains||[]));
    if(selected&&!available.has(selected))selected='';
    renderDomains();syncDomainUrl();
    $('#evidenceState').className='hidden';$('#evidenceContent').classList.remove('hidden');$('#evidenceHealth').textContent=`${fmt(articles.length)} resumos verificados`;$('#evidenceHealth').className='status-pill ok';
  }catch(error){$('#evidenceState').className='error';$('#evidenceState').innerHTML=`<strong>Evidence Explorer indisponível.</strong><div>${esc(error.message)}</div>`;$('#evidenceHealth').textContent='contexto indisponível';$('#evidenceHealth').className='status-pill bad'}
}
function domainRows(){const counts={};for(const row of articles){for(const domain of row.review_profile?.operational_domains||[]){counts[domain]=(counts[domain]||0)+1}}return Object.entries(counts).sort((a,b)=>b[1]-a[1])}
function renderDomains(){const rows=domainRows();if(!selected&&rows.length)selected=rows[0][0];$('#domainCards').innerHTML=rows.map(([domain,count])=>`<button type="button" class="domain-explorer-card${selected===domain?' active':''}" data-domain="${esc(domain)}"><span>${esc(labels[domain]||domain)}</span><strong>${fmt(count)}</strong><small>${(100*count/Math.max(1,articles.length)).toLocaleString('pt-BR',{maximumFractionDigits:1})}% do Tier A</small></button>`).join('');renderDetail()}
function renderDetail(){if(!selected)return;const rows=articles.filter(row=>(row.review_profile?.operational_domains||[]).includes(selected));const classCounts={};const routeCounts={};for(const row of rows){const cls=row.review_profile?.primary_document_class||row.document_class||'unclassified';classCounts[cls]=(classCounts[cls]||0)+1;for(const route of row.routes||[])routeCounts[route]=(routeCounts[route]||0)+1}const classes=Object.entries(classCounts).sort((a,b)=>b[1]-a[1]).slice(0,6);$('#domainTitle').textContent=labels[selected]||selected;$('#domainMeta').textContent=`${fmt(rows.length)} documentos · B-NORM ${fmt(routeCounts['B-NORM']||0)} · C-STRUCT ${fmt(routeCounts['C-STRUCT']||0)}`;$('#domainClassMix').innerHTML=classes.map(([key,value])=>`<span class="mini-pill">${esc(classLabels[key]||key)} · ${fmt(value)}</span>`).join('');$('#domainArticles').innerHTML=rows.slice(0,30).map(row=>`<article class="evidence-article"><div><strong>${esc(row.title||'Sem título')}</strong><small>${esc([row.year,row.source_provider,row.review_profile?.primary_document_class&&classLabels[row.review_profile.primary_document_class]].filter(Boolean).join(' · '))}</small></div><div class="detail-chips">${(row.routes||[]).map(route=>`<span class="mini-pill">${esc(route)}</span>`).join('')}</div></article>`).join('')||'<p class="small-state">Nenhum artigo neste domínio.</p>';$('#domainNote').textContent='Lista de navegação baseada em perfil determinístico. Não é inclusão, exclusão, qualidade ou recomendação.'}
$('#domainCards').addEventListener('click',event=>{const button=event.target.closest('[data-domain]');if(!button)return;selected=button.dataset.domain;syncDomainUrl();renderDomains()});
load();