const REVIEW_TYPE='NUTEV_HUMAN_SYNTHESIS_REVIEW_DRAFT_V1';
const BRIEF_TYPE='NUTEV_HUMAN_SYNTHESIS_BRIEF_V1';
const RELATIONS=['CONVERGENT','DIVERGENT','COMPLEMENTARY','NOT_COMPARABLE','UNCLEAR'];
const DIMENSIONS=['population','construct_intervention','outcome','timeframe'];
const RELATION_LABELS={CONVERGENT:'Convergent',DIVERGENT:'Divergent',COMPLEMENTARY:'Complementary',NOT_COMPARABLE:'Not comparable',UNCLEAR:'Unclear'};
const DIMENSION_LABELS={population:'Population',construct_intervention:'Construct / intervention',outcome:'Outcome',timeframe:'Timeframe'};
const DOMAIN_LABELS={nutrition_assessment:'Avaliação nutricional',dietary_counseling:'Aconselhamento alimentar',nutrition_prescription:'Prescrição nutricional',monitoring_follow_up:'Monitoramento / seguimento',food_skills_competencies:'Competências alimentares',food_literacy:'Food / nutrition literacy',social_context:'Contexto social da alimentação',food_based_guidance:'Orientação baseada em alimentos',nutrition_care_process:'Nutrition Care Process',lifestyle_medicine:'Medicina do Estilo de Vida',implementation_practice:'Implementação na prática'};
const state={search:null,review:null,fileName:'',integrityVerified:false,contextMatch:false};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const fmt=value=>new Intl.NumberFormat('pt-BR').format(Number(value||0));

async function fetchJson(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url}: HTTP ${response.status}`);return response.json()}
function stableValue(value){if(Array.isArray(value))return value.map(stableValue);if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).sort())out[key]=stableValue(value[key]);return out}return value}
async function sha256(value){const bytes=new TextEncoder().encode(JSON.stringify(stableValue(value)));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function scientificContent(review){return {export_type:review.export_type,canonical:review.canonical,search_id:review.search_id??null,context_version:review.context_version??null,question:review.question??null,reviewer:review.reviewer,decisions:review.decisions,guardrails:review.guardrails}}
function countBy(rows,getter){const counts={};for(const row of rows){const key=getter(row);if(!key)continue;counts[key]=(counts[key]||0)+1}return counts}
function resetBrief(message){state.review=null;state.integrityVerified=false;state.contextMatch=false;$('#briefContent').classList.add('hidden');$('#exportBrief').disabled=true;$('#printBrief').disabled=true;$('#briefHealth').textContent='revisão inválida';$('#briefHealth').className='status-pill bad';$('#verificationState').textContent=message}
function verifyItem(label,value,status){return `<div class="verify-item ${esc(status)}"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}

function validateDecision(decision){
  if(!decision||typeof decision!=='object')return false;if(!decision.human_entered||decision.canonical!==false)return false;if(!RELATIONS.includes(decision.relation))return false;if(!String(decision.reviewer||'').trim())return false;if(String(decision.rationale||'').trim().length<20)return false;if(!decision.anchor?.document_id||!decision.candidate?.document_id)return false;
  const comparability=decision.comparability||{};return DIMENSIONS.every(key=>['SIMILAR','DIFFERENT','UNCLEAR','NOT_AVAILABLE'].includes(comparability[key]));
}

async function verifyReview(review,fileName){
  const typeOk=review?.export_type===REVIEW_TYPE;const canonicalOk=review?.canonical===false;const decisionsOk=Array.isArray(review?.decisions)&&review.decisions.length>0&&review.decisions.every(validateDecision);const reviewerOk=Boolean(String(review?.reviewer||'').trim());
  let checksum='';let checksumOk=false;try{checksum=await sha256(scientificContent(review));checksumOk=Boolean(review?.content_sha256)&&checksum===review.content_sha256}catch{checksumOk=false}
  const searchOk=Boolean(state.search?.search_id)&&review?.search_id===state.search.search_id;const contextOk=Boolean(state.search?.context_version)&&review?.context_version===state.search.context_version;const questionOk=!state.search?.question||!review?.question||review.question===state.search.question;
  const currentMatch=searchOk&&contextOk&&questionOk;const allOk=typeOk&&canonicalOk&&decisionsOk&&reviewerOk&&checksumOk&&currentMatch;
  $('#verificationGrid').innerHTML=[verifyItem('Artifact type',typeOk?REVIEW_TYPE:String(review?.export_type||'missing'),typeOk?'pass':'fail'),verifyItem('Content SHA-256',checksumOk?`${checksum.slice(0,16)}…`:'INVALID / MISSING',checksumOk?'pass':'fail'),verifyItem('Search ID',searchOk?'MATCH':`${review?.search_id||'missing'} ≠ ${state.search?.search_id||'current n/d'}`,searchOk?'pass':'fail'),verifyItem('Context version',contextOk?'MATCH':`${review?.context_version||'missing'} ≠ ${state.search?.context_version||'current n/d'}`,contextOk?'pass':'fail'),verifyItem('Draft semantics',canonicalOk&&decisionsOk&&reviewerOk?`${review.reviewer} · ${fmt(review.decisions?.length)} decisions`:'INVALID DRAFT',canonicalOk&&decisionsOk&&reviewerOk?'pass':'fail')].join('');
  if(!allOk){resetBrief(`Arquivo ${fileName}: integridade/contexto não satisfeitos. O brief permanece bloqueado. SHA válido comprova integridade do conteúdo, não validade científica.`);return}
  state.review=review;state.fileName=fileName;state.integrityVerified=true;state.contextMatch=true;$('#verificationState').textContent=`${fileName} verificado localmente. SHA-256 e contexto correspondem ao Article 1 atual. Isso verifica integridade/proveniência; não transforma o rascunho em síntese canônica.`;$('#briefHealth').textContent='integridade verificada';$('#briefHealth').className='status-pill ok';$('#exportBrief').disabled=false;$('#printBrief').disabled=false;renderBrief()
}

function relationCounts(){return countBy(state.review?.decisions||[],row=>row.relation)}
function domainCounts(){return countBy(state.review?.decisions||[],row=>row.domain||'unmapped')}
function comparabilityCounts(){const output={};for(const dimension of DIMENSIONS){output[dimension]={SIMILAR:0,DIFFERENT:0,UNCLEAR:0,NOT_AVAILABLE:0}}for(const row of state.review?.decisions||[]){for(const dimension of DIMENSIONS){const value=row.comparability?.[dimension]||'UNCLEAR';output[dimension][value]=(output[dimension][value]||0)+1}}return output}

function renderKpis(){const decisions=state.review.decisions||[];const domains=new Set(decisions.map(row=>row.domain).filter(Boolean));const docs=new Set();for(const row of decisions){docs.add(row.anchor.document_id);docs.add(row.candidate.document_id)}const counts=relationCounts();const cards=[['Human decisions',decisions.length,'pairwise judgments imported'],['Documents',docs.size,'unique source-linked documents'],['Domains',domains.size,'represented in human review'],['Convergent',counts.CONVERGENT||0,'pairwise labels; not certainty'],['Divergent',counts.DIVERGENT||0,'pairwise labels; not proven contradiction'],['Review SHA',String(state.review.content_sha256||'').slice(0,12),'integrity identifier']];$('#briefKpis').innerHTML=cards.map(([label,value,note])=>`<article class="kpi-card"><span>${esc(label)}</span><strong>${esc(String(value))}</strong><small>${esc(note)}</small></article>`).join('')}
function renderLandscape(){const counts=relationCounts();const total=state.review.decisions.length||1;$('#relationshipLandscape').innerHTML=RELATIONS.map(relation=>{const value=counts[relation]||0;return `<article class="relation-summary ${relation}"><strong>${fmt(value)}</strong><span>${esc(RELATION_LABELS[relation])}</span><small>${(100*value/total).toLocaleString('pt-BR',{maximumFractionDigits:0})}% of reviewed pairs · descriptive only</small></article>`}).join('')}
function renderDomains(){const counts=domainCounts();const max=Math.max(1,...Object.values(counts));$('#domainReviewCoverage').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([domain,value])=>`<div class="brief-list-row"><div><strong>${esc(DOMAIN_LABELS[domain]||domain)}</strong><span>${fmt(value)} decisions</span></div><div class="brief-bar"><i style="--width:${100*value/max}%"></i></div></div>`).join('')}
function renderComparability(){const counts=comparabilityCounts();$('#comparabilityProfile').innerHTML=DIMENSIONS.map(dimension=>`<article class="comparability-card"><h3>${esc(DIMENSION_LABELS[dimension])}</h3>${['SIMILAR','DIFFERENT','UNCLEAR','NOT_AVAILABLE'].map(value=>`<div class="comparability-row"><span>${esc(value)}</span><strong>${fmt(counts[dimension][value]||0)}</strong></div>`).join('')}</article>`).join('')}
function sourceHtml(source,label){return `<div class="brief-source"><strong>${esc(label)} · ${esc(source.title||source.document_id)}</strong><p>${esc(source.result_text||'Result text unavailable in imported snapshot.')}</p></div>`}
function renderRelationships(){const rows=[...(state.review.decisions||[])].sort((a,b)=>String(a.domain||'').localeCompare(String(b.domain||''))||String(a.decision_id||'').localeCompare(String(b.decision_id||'')));$('#reviewedRelationships').innerHTML=rows.map(row=>`<article class="brief-decision"><div class="brief-decision-head"><div><strong>${esc(DOMAIN_LABELS[row.domain]||row.domain||'Unmapped domain')}</strong><small>${esc(row.reviewer)} · ${esc(row.reviewed_at||'date n/d')}</small></div><span class="brief-relation ${esc(row.relation)}">${esc(row.relation)}</span></div><div class="brief-pair">${sourceHtml(row.anchor,'Anchor')}${sourceHtml(row.candidate,'Compared')}</div><div class="brief-rationale"><strong>Reviewer rationale:</strong> ${esc(row.rationale)}</div><div class="brief-dimensions">${DIMENSIONS.map(key=>`<span>${esc(DIMENSION_LABELS[key])}: ${esc(row.comparability?.[key]||'UNCLEAR')}</span>`).join('')}</div></article>`).join('')}
function renderBrief(){renderKpis();renderLandscape();renderDomains();renderComparability();renderRelationships();$('#briefContent').classList.remove('hidden')}

function briefScientificContent(){const decisions=state.review.decisions||[];return {export_type:BRIEF_TYPE,canonical:false,integrity_verified:true,current_context_match:true,source_review_type:state.review.export_type,source_review_content_sha256:state.review.content_sha256,search_id:state.review.search_id,context_version:state.review.context_version,question:state.review.question,reviewer:state.review.reviewer,relationship_counts:relationCounts(),domain_counts:domainCounts(),comparability_counts:comparabilityCounts(),reviewed_decisions:decisions,guardrails:{source_review_is_noncanonical:true,integrity_verification_is_not_scientific_validation:true,relationship_counts_are_not_evidence_strength:true,convergent_is_not_certainty:true,divergent_is_not_proven_contradiction:true,brief_is_not_meta_analysis:true,brief_is_not_prisma:true}}}
async function exportBrief(){if(!state.integrityVerified||!state.contextMatch||!state.review)return;const content=briefScientificContent();const contentSha256=await sha256(content);const payload={...content,content_sha256:contentSha256,generated_at:new Date().toISOString(),artifact_semantics:'Presentation-ready human review brief. Integrity verified; scientific conclusions remain the reviewer’s responsibility.'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`nutev-human-synthesis-brief-${contentSha256.slice(0,12)}.json`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url)}

async function handleFile(file){if(!file)return;$('#briefHealth').textContent='verificando…';$('#briefHealth').className='status-pill';try{const review=JSON.parse(await file.text());await verifyReview(review,file.name)}catch(error){$('#verificationGrid').innerHTML='';resetBrief(`Não foi possível validar ${file.name}: ${error.message}`)}}
async function init(){try{state.search=await fetchJson('/agent-context/article1/SEARCH_STATE.json');$('#briefQuestion').textContent=state.search.question||'Article 1 — contexto científico do NutEV';$('#reviewFile').addEventListener('change',event=>handleFile(event.target.files?.[0]));$('#exportBrief').addEventListener('click',exportBrief);$('#printBrief').addEventListener('click',()=>window.print());$('#briefHealth').textContent='aguardando revisão';$('#briefHealth').className='status-pill'}catch(error){$('#verificationState').textContent=`Contexto atual indisponível: ${error.message}`;$('#briefHealth').textContent='contexto indisponível';$('#briefHealth').className='status-pill bad'}}

init();
